### PR TITLE
make headers editable

### PR DESCRIPTION
**Pull request by itisnajim**
## What kind of change does this PR introduce?

This PR introduces a feature that allows for greater customization of HTTP headers in the Supabase Dart library. but we need first to enable the customization also in the sub packages (realtime, storage and functions)

Everything is described here: 
https://github.com/supabase/supabase-dart/pull/185

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by Vinzent03 — CHANGES_REQUESTED** [review]
I guess we can remove the `{...Constants.defaultHeaders, ...headers},` construct [here](https://github.com/supabase/storage-dart/pull/57/files#diff-688e9d6bf7fba678f0379c8e146f41c6eb70208767c4124253bb5910d8b41287R43), when it's done in `StorageBucketApi` as well.

Additionally, I just noticed this is a breaking change since it's removing the setter. What we want to accomplish already works here, so I recommend doing that for v2.

**Comment by itisnajim** [comment]
> I guess we can remove the `{...Constants.defaultHeaders, ...headers},` construct [here](https://github.com/supabase/storage-dart/pull/57/files#diff-688e9d6bf7fba678f0379c8e146f41c6eb70208767c4124253bb5910d8b41287R43), when it's done in `StorageBucketApi` as well.
> 
> Additionally, I just noticed this is a breaking change since it's removing the setter. What we want to accomplish already works here, so I recommend doing that for v2.

which setter ? do you mean `setAuth`? it just moved from [here](https://github.com/supabase/storage-dart/pull/57/files#diff-688e9d6bf7fba678f0379c8e146f41c6eb70208767c4124253bb5910d8b41287L54) to [here](https://github.com/supabase/storage-dart/pull/57/files#diff-30e06b28a8454694ca6d8151f99763d1c4e75318789ca7705ad729a3d3d3bcd9R122)

**Comment by Vinzent03** [comment]
Sorry I meant the fact that `headers` is now private and you cant use `client.headers = {}`.

**Comment by itisnajim** [comment]
> Sorry I meant the fact that `headers` is now private and you cant use `client.headers = {}`.

client its an extension of StorageBucketApi `SupabaseStorageClient extends StorageBucketApi`, so i think to add a new header `storageClient.headers['new-key'] = 'new-val';` should work, and to remove: `storageClient.headers.remove('new-key');`

**Comment by itisnajim** [comment]
> Yeah sure, but before it was possible to assign a new value to `headers`. Now you can only modify an existing object. The point is that previous code could break.

Ah Yes, that's a valid point. Previously, it was possible to assign a new value to headers, but now you can only modify an existing object. However, the reason for this change is to align the storage client with all other clients (realtime, functions, and supabase) that all have private headers and an exposed getter.

I believe that having a getter is sufficient for modifying the headers, and it is an advanced use case that is rarely needed. If someone wants to dynamically modify the headers at runtime, they can use the code below to inject a new header:
```dart
final newHeader = {'new-key': 'new val'};
supabaseClient.headers.addAll(newHeader);
// or supabaseClient.headers['new-key'] = 'new val';
supabaseClient.functions.headers.addAll(newHeader);
supabaseClient.storage.headers.addAll(newHeader);
supabaseClient.realtime.headers.addAll(newHeader);
// for realtime you may need to unsubscribe and resubscribe to all channels to apply the new header
```

In my opinion, what we have in the PRs is sufficient for this use case or situation.

**Comment by Vinzent03** [comment]
Yeah we already concluded that in supabase/functions-dart#19. That's not my point. I'm just saying I wouldn't merge this pr before v2, because we can already access the `headers`. That's all we need for `supabase-dart`. This pr doesn't provide more functionality, it only shrinks existing. And that's fine, but may break code of people using the existing `client.headers = foo` functionality.

**Comment by itisnajim** [comment]
> Yeah we already concluded that in [supabase/functions-dart#19](https://github.com/supabase/functions-dart/pull/19). That's not my point. I'm just saying I wouldn't merge this pr before v2, because we can already access the `headers`. That's all we need for `supabase-dart`. This pr doesn't provide more functionality, it only shrinks existing. And that's fine, but may break code of people using the existing `client.headers = foo` functionality.

Thank you for sharing your thoughts on this. I understand your concern that the removal of the client.headers = foo functionality may break existing code for some users. However, this was to align the Storage client with the other Supabase clients and the users can still modify the headers using the headers.addAll() method or by accessing the headers object directly.
If there are any potential issues that may arise from the removal of the client.headers = foo functionality, I would be happy to address them and work towards finding a solution that works for everyone 👍.

**Comment by dshukertjr** [comment]
@itisnajim @Vinzent03 
I'm just going to close this assuming we are good to do so since we can now edit headers, but let me know if I'm wrong.

**Pull request closed without merging**
